language: node_js
sudo: false
node_js:
  - node
services:
  - mongodb
jobs:
  include:
    - stage: login
      before_script:
        - cd src/backend/login
        - npm install
      script: npm test
    - stage: defuncion
      before_script:
        - cd src/backend/defuncion
        - npm install
      script: npm test
#script:
#  - npm test


# https://stackoverflow.com/questions/14468464/how-to-specify-a-build-folder-in-travis