# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"         # Ubuntu Server 14.04 LTS
  config.vm.hostname = "ubuntu"             # Nombre de la maquina interno
  config.vm.provider "virtualbox" do |vb|   # Parametros para VB
    vb.name = "first_deploy"    # Nombre de la maquina en interfaz VB
  end

  config.vm.provision "ansible" do |ansible|  # Parametros para Ansible
    ansible.playbook = "playbook.yml"
  end

end